class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'extract'
        self.TarMirrorCommand = 'archive'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'stop'
        self.ListCommand = 'search'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AuthListCommand = 'authlist'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'tarytdl'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'info'
        self.TotranslateCommand = 'tr'
        self.PasteCommand = 'paste'
        self.SystemstatsCommand= 'system'

BotCommands = _BotCommands()
